### ISSUE TITLE
can't find include files

### ISSUE THREAD

**Issue by LXY666def** [jaesung-cs/vkgs#18]
Hi, i'm trying to learn this fantastic project. But when i clone your project, i can't find include files below which are included in `src\vkgs\engine\engine.cc`, so i wonder where i can find them? thank you for replying me and your awesome work!
```cpp
#include "generated/parse_ply_comp.h"
#include "generated/projection_comp.h"
#include "generated/rank_comp.h"
#include "generated/inverse_index_comp.h"
#include "generated/splat_vert.h"
#include "generated/splat_frag.h"
#include "generated/splat_geom_vert.h"
#include "generated/splat_geom_geom.h"
#include "generated/color_vert.h"
#include "generated/color_frag.h"
```

**Comment by jaesung-cs** [comment]
Hi,

those files are generated when you run cmake:
```bash
$ cmake . -B build
$ cmake --build build --config Release
```
generation command is defined as:
https://github.com/jaesung-cs/vkgs/blob/52a4bc159b54bf75e95df446c67130335c521441/CMakeLists.txt#L17-L43
https://github.com/jaesung-cs/vkgs/blob/52a4bc159b54bf75e95df446c67130335c521441/CMakeLists.txt#L87-L96
if the cmake build command runs successfully, you will find cmake output message at the beginning like this: 
```
  1>Checking Build System
  Compiling C:/workspace/vkgs/src/generated/color_frag.h
  C:/workspace/vkgs/src/shader/color.frag
  Building Custom Rule C:/workspace/vkgs/CMakeLists.txt
  Compiling C:/workspace/vkgs/src/generated/color_vert.h
  C:/workspace/vkgs/src/shader/color.vert
  Building Custom Rule C:/workspace/vkgs/CMakeLists.txt
...
```
please confirm you have installed VulkanSDK>=1.2 in your system:
```bash
$ vulkaninfo | grep Version  # (Linux/MacOS)
$ vulkaninfo.exe | findstr Version  # (Windows)
Vulkan Instance Version: 1.3.280
```

**Comment by LXY666def** [comment]
thanks! i have solved the problem
