### ISSUE TITLE
Training Impl

### ISSUE THREAD

**Issue by zzdev18** [jaesung-cs/vkgs#20]
Hi, is the training implementation on your time line yet?

Or rather, can the Graphics Pipelines be modified somehow to support gradients tracking? Currently the information about the contributing gaussians to each pixel is missing. can they be extracted in anyway?

Fantastic project btw🥇

**Comment by jaesung-cs** [comment]
Hi,

I have been thinking about using graphics pipeline in train step, and found it a very difficult problem.

When I implemented viewer, I had a certain degree of expectation about how much it will be faster compared to CUDA implementation. Rendering only involves a forward step.
In backward step, however, my expectation is not really as high as in forward step. A pixel screen buffer and AtomicAdd operations for every fragment are inevitable, lessening the benefit of Graphics pipeline. It reminds me that the small MLP introduced in instant-ngp was 10x faster in forward step, but only 2x faster in backward step.

> Currently the information about the contributing gaussians to each pixel is missing.

You are right. Alpha blending is done by Vulkan. But for backward step, a pixel screen buffer for accumulating contributing gaussians will be necessary.

So, I don't know how beneficial it is to write backward step in Vulkan. If you have breakdowns in each step in a training iteration, it would be helpful for me to decide if it is worth trying.
